### ISSUE TITLE
IDEA

### ISSUE THREAD

**Issue by sjk0503** [sjk0503/chatAPP#1]
주제  아이디어
1. 텍스트 게임: 하린
2. 식단 관리: 압돌라
3. 관광지 여행지 추천 챗봇: 하린, 태현
4. 일정 관리 챗봇: 성재
5. 장애인, 노약자용 챗봇: 성재, 태현 - 음성인식 + 보호자 + 보호자 연동 앱 -> 장애인/어린아이 겨냥
6.

**Comment by pqud** [comment]
- [ ] 조심해야 하는 음식
- [ ] 추천 음식점
- [ ] 음식/택시비/ 평균값 
- [ ] 현재 위치 기준 근처 위험 지역 알림 * 
- [ ] 안내(탑승 위치 등)
- [ ] 사진 찍어서 번역+추가 정보 *
- [ ] 위험 사항 대처 방법 *
- [ ] 호텔 예약
- [ ] 여행 일정 기능
- [ ] 우버
- [ ] 패스/ 비자/ 여행 시 필요한 서류 등의 정보
- [ ] 특산품
- [ ] 인터넷 안되는 상황에서도 사용 가능

*는 앱 필수 기능
